answers for lesson 1
trca831/node-express-course pull request #1
Opened 2023-06-14 03:57 UTC by trca831

Need additional assistance with prompter.js

2023-06-14 22:01 UTC, jamisonvalentine commented on 01-node-tutorial/answers/10-fs-sync.js
The order is wrong here: you want to write to the file then read it... but I think you get the concept.

2023-06-14 22:05 UTC, jamisonvalentine approved these changes

2023-09-28 11:08 UTC, leo-mutuku requested changes
Hi Tracy, I have reviewed the assignment, well done and clearly understood the concepts. However I recomend a 1:1 review especially on node modules. I will be reviewing the lesson on my 1:1 section friday and satarday.

2023-10-14 04:30 UTC, leo-mutuku approved these changes
Week1 assessment completed.

2023-10-14 04:30 UTC, leo-mutuku commented on 01-node-tutorial/answers/prompter.js
Approved

2023-10-17 02:34 UTC, merged

2024-05-01 19:50 UTC, GinaCastromonte reviewed
Great Job Tracy! Looks like you adjusted your changes.